[package]
name = "omnistack-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
env_logger = "0.11.2"
clap = { version = "4.5.2", features = ["derive"] }
tikv-jemallocator = "0.5"
omnistack-core = { path = "../omnistack-core" }

[features]
