[package]
name = "omnistack-core"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
once_cell = "1.18.0"
autocxx = "0.26.0"
cxx = "1.0"
colored = "2.0.4"
ctor = "0.2.5"
concat-idents = "1.1.5"

[build-dependencies]
autocxx-build = "0.26.0"
pkg-config = "0.3.27"
cfg-if = "1.0"

[features]
default = ["dpdk"]
dpdk = []
