[package]
name = "omnistack-core"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
colored = "2.0.4"
concat-idents = "1.1.5"
static_init = "1.0.3"
autocxx = "0.26.0"
cxx = "1.0"
json = "0.12.4"
crossbeam = "0.8.2"

[build-dependencies]
autocxx-build = "0.26.0"
pkg-config = "0.3.27"

[features]
default = ["dpdk"]
dpdk = []
