[package]
name = "omnistack"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
env_logger = "0.11.2"
omnistack-core = { path = "../omnistack-core" }
omnistack-sys = { path = "../omnistack-sys" }

[features]
